import { FormEvent, useMemo, useState } from "react";
import { Activity, ArrowRight, Brain, KeyRound, LockKeyhole, Search, Sparkles, UploadCloud } from "lucide-react";
import { useBrainClient } from "./client";
import { Detail } from "./Detail";
import GraphPreview from "./GraphPreview";
import type { View } from "./routes";

type Props = { view: View; demo: boolean; onNavigate: (view: View) => void; onImported?: () => Promise<void>; theme: "light" | "dark"; onTheme: (theme: "light" | "dark") => void; settingsSection?: string };
const providers = [
  { name: "GitHub", kind: "Developer", detail: "Repository documentation and decisions", icon: "GH" },
  { name: "Google Drive", kind: "Workspace", detail: "Documents and shared files", icon: "GD" },
  { name: "Notion", kind: "Workspace", detail: "Pages and team knowledge", icon: "N" },
  { name: "OneDrive", kind: "Workspace", detail: "Organization files", icon: "OD" },
  { name: "Web URL", kind: "Web", detail: "Public articles and pages", icon: "↗" },
];
const memories = [
  { id: "mem-1", title: "Onboarding needs one named owner", source: "Customer interview", status: "Awaiting review", date: "Sep 22", related: "Assign one owner for the first customer week." },
  { id: "mem-2", title: "Teams reuse decisions when rationale travels with them", source: "Product notes", status: "Linked to approved knowledge", date: "Sep 19", related: "Decision records include original rationale." },
  { id: "mem-3", title: "Support requests cluster around setup handoff", source: "Support synthesis", status: "Awaiting review", date: "Sep 17", related: "No approved link yet" },
];
const requests = [
  { id: "req-a31", operation: "Search", status: "Success", latency: "42 ms", time: "10:42", detail: "Returned three cited knowledge items" },
  { id: "req-a30", operation: "Capture", status: "Success", latency: "210 ms", time: "10:38", detail: "Created a new versioned source" },
  { id: "req-a29", operation: "Ask", status: "Unavailable", latency: "—", time: "10:21", detail: "No answer generated because retrieval was unavailable" },
];
const turns = [
  { id: "turn-01", title: "What did we decide about onboarding?", actor: "Research agent", time: "Today, 10:42", status: "Sample" },
  { id: "turn-02", title: "Summarize the launch retrospective", actor: "Codex", time: "Yesterday, 16:18", status: "Sample" },
];

function Banner({ demo, children }: { demo: boolean; children?: React.ReactNode }) { return <div className="preview-banner"><Sparkles size={16}/><strong>{demo ? "Demo workspace" : "Design preview"}</strong><span>{children ?? "This interface uses synthetic data. Changes here stay in your browser and do not reach the Brain API."}</span></div>; }
function Panel({ title, children, action }: { title: string; children: React.ReactNode; action?: React.ReactNode }) { return <section className="preview-panel"><header><h2>{title}</h2>{action}</header>{children}</section>; }

function Row({ children, onClick }: { children: React.ReactNode; onClick?: () => void }) { return <button type="button" className="preview-row" onClick={onClick}>{children}<ArrowRight size={16}/></button>; }

function PreviewContent({ view, demo, onImported, theme, onTheme, settingsSection = "General" }: Props) {
  const client = useBrainClient();
  const [search, setSearch] = useState("");
  const [selected, setSelected] = useState<string | null>(null);
  const [tab, setTab] = useState(view === "import" ? "Text" : view === "agents" ? "Hermes" : view === "settings" ? "General" : "All");
  const [notice, setNotice] = useState("");
  const [busy, setBusy] = useState(false);
  const [importError, setImportError] = useState("");
  const [draftKeys, setDraftKeys] = useState<Array<{ name: string; scope: string; expiry: string }>>([]);
  const [policy, setPolicy] = useState({ recommendations: false, reminders: false });

  const filteredProviders = useMemo(() => providers.filter(p => `${p.name} ${p.kind}`.toLowerCase().includes(search.toLowerCase()) && (tab === "All" || p.kind === tab)), [search, tab]);
  const selectedProvider = providers.find(p => p.name === selected);
  const selectedMemory = memories.find(m => m.id === selected);
  const selectedRequest = requests.find(r => r.id === selected);
  const selectedTurn = turns.find(t => t.id === selected);

  async function importText(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const form = event.currentTarget;
    const data = new FormData(form);
    setBusy(true); setImportError("");
    try {
      await client.createSource({ title: String(data.get("title")), kind: String(data.get("kind")), sensitivity: String(data.get("sensitivity")), content: String(data.get("content")) });
      await onImported?.();
      setNotice(demo ? "Sample source captured locally. Review its proposal in Inbox." : "Source captured. Review its proposals in Inbox.");
      form.reset();
    } catch (error) { setImportError(error instanceof Error ? error.message : "Import failed. Your text is still here; try again."); }
    finally { setBusy(false); }
  }

  if (view === "import") return <div className="preview-page narrow-page">
    {demo && <Banner demo/>}<div className="tabs" role="tablist" aria-label="Import method">{["Text", "Files", "URL"].map(x=><button role="tab" aria-selected={tab===x} className={tab===x?"active":""} onClick={()=>setTab(x)} key={x}>{x}</button>)}</div>
    {tab === "All" || tab === "Text" ? <Panel title="Capture original text"><form className="import-form" onSubmit={importText}><label>Title<input name="title" required minLength={3} maxLength={240} placeholder="e.g. Founder interview — September"/></label><div className="form-pair"><label>Source type<select name="kind" defaultValue="note"><option value="note">Note</option><option value="research">Research</option><option value="interview">Interview</option><option value="decision">Decision</option></select></label><label>Visibility<select name="sensitivity" defaultValue="private"><option value="private">Private</option><option value="internal">Internal</option><option value="public">Public</option></select></label></div><label>Source content<textarea name="content" required minLength={20} maxLength={100000} rows={10} placeholder="Paste original material here…"/></label><p className="muted-line">The original is preserved. Extracted ideas enter your review inbox.</p>{importError && <p role="alert" className="inline-error">{importError}</p>}<button className="primary-button" disabled={busy}>{busy ? "Capturing…" : "Capture and extract"}</button></form></Panel> : <Panel title={tab === "Files" ? "Import files" : "Add a URL"}><div className="preview-empty"><UploadCloud size={32}/><h3>{tab === "Files" ? "File import preview" : "URL import preview"}</h3><p>{tab === "Files" ? "A staged upload area is shown for design review. File processing is not connected yet." : "A URL field is shown for design review. Web ingestion is not connected yet."}</p>{tab === "Files" ? <label className="file-preview">Choose local files<input type="file" multiple onChange={e=>setNotice(`${e.target.files?.length ?? 0} file(s) selected locally. Nothing uploaded.`)}/></label> : <div className="form-pair"><input type="url" aria-label="Page URL" placeholder="https://example.com/article" onChange={e=>setSearch(e.target.value)}/><button className="secondary-button" onClick={()=>setNotice(search ? "URL staged locally. Import is not yet available." : "Enter a URL first.")}>Stage URL</button></div>}</div></Panel>}
    {notice && <p role="status" className="inline-notice">{notice}</p>}
  </div>;

  if (view === "workspaces") return <div className="preview-page narrow-page"><Banner demo={demo}>Workspace browsing is a design preview. Tags organize material; they are not authorization boundaries.</Banner><Panel title="Workspaces" action={<button className="secondary-button" onClick={()=>setSelected("New workspace")}>New workspace · Preview</button>}><div className="preview-table-head"><span>Workspace</span><span>Knowledge</span><span>Activity</span></div><Row onClick={()=>setSelected("Personal Brain")}><strong>Personal Brain</strong><span>63 approved items</span><small>Today</small></Row><Row onClick={()=>setSelected("Product research")}><strong>Product research</strong><span>18 approved items</span><small>Yesterday</small></Row></Panel>{selected && <Detail title={selected} onClose={()=>setSelected(null)}><p>Sample workspace details and member roles. Management actions are not connected.</p><div className="detail-stat"><span>Sources</span><strong>24</strong></div><div className="detail-stat"><span>Approved knowledge</span><strong>63</strong></div></Detail>}</div>;

  if (view === "working-memory") return <div className="preview-page narrow-page"><Banner demo={demo}/><div className="preview-toolbar"><label className="search-field"><Search size={17}/><input type="search" placeholder="Search working memory" value={search} onChange={e=>setSearch(e.target.value)}/></label><select aria-label="Memory status" value={tab} onChange={e=>setTab(e.target.value)}><option>All</option><option>Awaiting review</option><option>Linked to approved knowledge</option></select></div><Panel title="Working memory"><div className="preview-table-head"><span>Memory</span><span>Source</span><span>Status</span></div>{memories.filter(m=>`${m.title} ${m.source}`.toLowerCase().includes(search.toLowerCase())&&(tab==="All"||m.status===tab)).map(m=><Row key={m.id} onClick={()=>setSelected(m.id)}><strong>{m.title}</strong><span>{m.source}</span><small>{m.status}</small></Row>)}</Panel>{selectedMemory && <Detail title={selectedMemory.title} onClose={()=>setSelected(null)}><p>{selectedMemory.status}</p><div className="detail-stat"><span>Original source</span><strong>{selectedMemory.source}</strong></div><div className="detail-stat"><span>Date</span><strong>{selectedMemory.date}</strong></div><h3>Relationship to approved knowledge</h3><p>{selectedMemory.related}</p></Detail>}</div>;

  if (view === "graph") return <div className="preview-page graph-page"><Banner demo={demo}/><GraphPreview/></div>;

  if (view === "connectors") return <div className="preview-page narrow-page"><Banner demo={demo}>Provider configuration is a preview. No OAuth or synchronization occurs.</Banner><div className="preview-toolbar"><div className="tabs">{["All", "Developer", "Workspace", "Web"].map(x=><button className={tab===x?"active":""} key={x} onClick={()=>setTab(x)}>{x}</button>)}</div><label className="search-field"><Search size={17}/><input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search connectors"/></label></div><Panel title="Available providers">{filteredProviders.map(p=><Row key={p.name} onClick={()=>setSelected(p.name)}><span className="provider-icon">{p.icon}</span><strong>{p.name}</strong><span>{p.detail}</span><small>Preview</small></Row>)}</Panel>{selectedProvider && <Detail title={selectedProvider.name} onClose={()=>setSelected(null)}><p>{selectedProvider.detail}</p><p>Connection settings are designed but not enabled for this Brain. No data will be imported from this provider yet.</p><form className="import-form" onSubmit={e=>{e.preventDefault();setNotice("Configuration preview held locally. No connection or sync was started.")}}><label>{selectedProvider.name === "GitHub" ? "Repository" : "Folder or collection"}<input placeholder={selectedProvider.name === "GitHub" ? "organization/repository" : "Sample collection name"} required/></label><label>Sync scope<select><option>Selected documents only</option><option>Entire collection</option></select></label><label>Visibility<select><option>Private</option><option>Internal</option></select></label><button className="secondary-button">Review configuration preview</button>{notice&&<p role="status" className="inline-notice">{notice}</p>}</form></Detail>}</div>;

  if (view === "api-keys") return <div className="preview-page narrow-page"><Banner demo={demo}>Key creation and revocation are local design previews. No credential is issued.</Banner><Panel title="API keys" action={<button className="secondary-button" onClick={()=>setSelected("Create key")}>Create key · Preview</button>}><div className="preview-table-head"><span>Name</span><span>Scope</span><span>Expires</span></div>{draftKeys.length ? draftKeys.map(k=><Row key={k.name} onClick={()=>setSelected(k.name)}><strong>{k.name}</strong><span>{k.scope}</span><small>{k.expiry}</small></Row>) : <div className="preview-empty"><KeyRound size={28}/><h3>No preview keys yet</h3><p>Try the creation flow to inspect scope and expiry controls. No secret is generated.</p></div>}</Panel>{selected && <Detail title={selected} onClose={()=>setSelected(null)}>{selected==="Create key" ? <form className="import-form" onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget);setDraftKeys(v=>[...v,{name:String(d.get("name")),scope:String(d.get("scope")),expiry:String(d.get("expiry"))}]);setSelected(null);setNotice("Preview key row created locally. No credential was issued.")}}><label>Name<input name="name" required placeholder="Development key"/></label><label>Scope<select name="scope"><option>Read only</option><option>Read and write</option></select></label><label>Expiry<select name="expiry"><option>30 days</option><option>90 days</option></select></label><button className="primary-button">Add preview row</button></form> : <><p>Dummy entry. No credential exists.</p><button className="secondary-button" onClick={()=>{setDraftKeys(draftKeys.filter(k=>k.name!==selected));setSelected(null)}}>Remove preview row</button></>}</Detail>}{notice&&<p role="status" className="inline-notice">{notice}</p>}</div>;

  if (view === "agents") return <div className="preview-page narrow-page"><Banner demo={demo}>Setup follows the repository's documented read-only integration. Connection status is not available here.</Banner><Panel title="Connected agents"><div className="preview-empty"><Brain size={28}/><h3>Connection status unavailable</h3><p>This page does not register or monitor agents.</p></div></Panel><Panel title="Connect an agent"><div className="tabs">{["Hermes", "Codex", "Claude"].map(x=><button key={x} className={tab===x?"active":""} onClick={()=>setTab(x)}>{x}</button>)}</div><div className="setup-steps"><div><span>01</span><div><strong>Register the local stdio server in {tab}</strong><p>Install this project, then enter the command and database location in your client's MCP configuration. Replace the example paths with your own absolute paths.</p><pre>{JSON.stringify({command:"/absolute/path/to/open-intelligence-brain/.venv/bin/open-brain-mcp",args:[],env:{BRAIN_DATABASE_URL:"sqlite:////absolute/path/to/open-intelligence-brain/brain.db"}},null,2)}</pre></div></div><div><span>02</span><div><strong>Verify read-only retrieval</strong><p>Available tools: brain_status, search_brain, ask_brain, list_pending_reviews, inspect_brain_integrity. Only approved knowledge enters canonical search and answers. Approval stays in the console.</p></div></div><div><span>03</span><div><strong>Remote HTTP adapter</strong><p>GET /api/v1/mcp/tools and POST /api/v1/mcp/call require your deployment's X-Brain-Token header. The HTTP adapter is a project-specific API; automatic hosted MCP registration is unsupported in this interface.</p><p>Client-specific registration follows that client's documentation. No credential or shared hosted endpoint is supplied here.</p></div></div></div></Panel></div>;

  if (view === "requests") return <div className="preview-page narrow-page"><Banner demo={demo}>Request telemetry shown here is synthetic and separate from domain Audit events.</Banner><div className="preview-toolbar"><div className="tabs">{["All", "Search", "Capture", "Ask"].map(x=><button key={x} className={tab===x?"active":""} onClick={()=>setTab(x)}>{x}</button>)}</div><select aria-label="Status filter" value={search} onChange={e=>setSearch(e.target.value)}><option value="">All statuses</option><option>Success</option><option>Unavailable</option></select></div><div className="request-metrics"><div><small>Requests</small><strong>3</strong></div><div><small>Successful</small><strong>2</strong></div><div><small>Avg search latency</small><strong>42 ms</strong></div></div><Panel title="Recent requests"><div className="preview-table-head"><span>Operation</span><span>Status</span><span>Latency</span></div>{requests.filter(r=>(tab==="All"||r.operation===tab)&&(!search||r.status===search)).map(r=><Row key={r.id} onClick={()=>setSelected(r.id)}><strong>{r.operation}</strong><span>{r.status}</span><small>{r.latency}</small></Row>)}</Panel>{selectedRequest&&<Detail title={selectedRequest.id} onClose={()=>setSelected(null)}><p>{selectedRequest.detail}</p><div className="detail-stat"><span>Time</span><strong>{selectedRequest.time}</strong></div><div className="detail-stat"><span>Status</span><strong>{selectedRequest.status}</strong></div></Detail>}</div>;

  if (view === "insights") return <div className="preview-page narrow-page"><Banner demo={demo}>This is a sample usage report. Live knowledge counts remain in Analytics.</Banner><Panel title="Sample audience insights"><div className="insight-lead"><div><small>Summary</small><h3>Questions cluster around onboarding and decisions.</h3><p>Illustrative report drawn from synthetic activity. No user profile analysis is running.</p></div><div className="insight-kpis"><div><small>Sample users</small><strong>42</strong></div><div><small>Segments</small><strong>3</strong></div></div></div><div className="insight-bars"><div><span>Onboarding questions</span><b style={{width:"62%"}}/><strong>62%</strong></div><div><span>Decision history</span><b style={{width:"25%"}}/><strong>25%</strong></div><div><span>Other</span><b style={{width:"13%"}}/><strong>13%</strong></div></div></Panel></div>;

  if (view === "turns") return <div className="preview-page narrow-page"><Banner demo={demo}>Turns are example activity. No agent execution is being represented as live.</Banner><Panel title="Activity timeline">{turns.map(t=><Row key={t.id} onClick={()=>setSelected(t.id)}><Activity size={17}/><strong>{t.title}</strong><span>{t.actor}</span><small>{t.time}</small></Row>)}</Panel>{selectedTurn&&<Detail title={selectedTurn.title} onClose={()=>setSelected(null)}><p>{selectedTurn.actor} · {selectedTurn.time}</p><p>Example turn detail with cited context and status. No execution occurred.</p></Detail>}</div>;

  if (view === "proactivity") return <div className="preview-page narrow-page"><Banner demo={demo}>Policy controls are interactive locally only. Nothing is scheduled or saved to the server.</Banner><Panel title="Proactivity policy"><p className="panel-intro">Choose which kinds of suggestions a future Brain may offer.</p><label className="toggle-row"><span><strong>Knowledge recommendations</strong><small>Suggest connections and possible conflicts for review.</small></span><input type="checkbox" checked={policy.recommendations} onChange={e=>setPolicy({...policy,recommendations:e.target.checked})}/></label><label className="toggle-row"><span><strong>Review reminders</strong><small>Remind owners about proposals awaiting a decision.</small></span><input type="checkbox" checked={policy.reminders} onChange={e=>setPolicy({...policy,reminders:e.target.checked})}/></label><button className="secondary-button" onClick={()=>setNotice("Preview policy held in this browser only.")}>Review policy preview</button></Panel>{notice&&<p role="status" className="inline-notice">{notice}</p>}</div>;

  if (view === "settings") return <div className="preview-page narrow-page"><Banner demo={demo}>Appearance is saved in this browser. Administration controls are design previews.</Banner>{settingsSection === "General" ? <Panel title="Organization"><div className="setting-row"><div><strong>Appearance</strong><p>Choose a comfortable theme for the interface.</p></div><select aria-label="Appearance" value={theme} onChange={e=>onTheme(e.target.value as "light"|"dark")}><option value="dark">Dark</option><option value="light">Light</option></select></div><div className="setting-row"><div><strong>Organization context</strong><p>Future profile settings will live here.</p></div><span className="status-pill">Preview</span></div></Panel> : <Panel title={settingsSection}><div className="preview-empty"><LockKeyhole size={26}/><h3>{settingsSection} administration preview</h3><p>Settings for {settingsSection.toLowerCase()} are not connected in this UI phase.</p></div></Panel>}</div>;

  return null;
}

export function PreviewPage(props: Props) {
  const [entered, setEntered] = useState(props.demo || props.view === "import" || props.view === "settings");
  if (!entered) return <div className="preview-page narrow-page"><section className="preview-panel preview-empty"><LockKeyhole size={28}/><h2>This capability is not connected yet</h2><p>Explore an interactive design preview with synthetic examples. Your workspace records and permissions remain separate.</p><button className="secondary-button" onClick={()=>setEntered(true)}>Explore design preview</button></section></div>;
  return <PreviewContent {...props}/>;
}
